from pathlib import Path
DATABASE_FILE=Path.home()/"worktimer_enterprise.db"
DEFAULT_IDLE_THRESHOLD=300
WM_WTSSESSION_CHANGE=0x02B1
WTS_SESSION_LOCK=0x0007
WTS_SESSION_UNLOCK=0x0008
NOTIFY_FOR_THIS_SESSION=0
